name: 'Initial Boostrap for Sandbox Infrastructure'

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  AWS_REGION: us-west-2
  TF_VAR_bucket_name: sandbox-infra-opentofu-alpha
  ENVIRONMENT: alpha
  OPENTOFU_DIRECTORY: opentofu

jobs:
  boostrap-infra:
    name: 'Boostrap initial infrastructure'
    runs-on: ubuntu-24.04
    outputs:
      s3_bucket_name: ${{ steps.opentofu-backend.outputs.s3_bucket_name }}
      initial_iam_role: ${{ steps.initial-bootstrap.outputs.role_arn }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2.0.2
        with:
          tofu_version_file: .opentofu-version
          tofu_wrapper: false

      - name: Check if OpenTofu Backend Bucket Exists
        id: check-backend-bucket
        run: |
          if aws s3api head-bucket --bucket "${{ env.TF_VAR_bucket_name }}"; then
            echo "Bucket exists."
            echo "create_backend_bucket=false" >> $GITHUB_OUTPUT
          else
            echo "Bucket does not exist."
            echo "create_backend_bucket=true" >> $GITHUB_OUTPUT
          fi

      - name: Create OpenTofu Backend Bucket
        id: opentofu-backend
        if: steps.check-backend-bucket.outputs.create_backend_bucket == 'true'
        working-directory: ${{ env.OPENTOFU_DIRECTORY }}/000-backend-creation
        run: |
          tofu init
          tofu fmt -check
          tofu validate
          tofu plan -out=tfplan
          tofu apply -auto-approve tfplan

#      - name: Setup iamlive
#        uses: marcofranssen/setup-iamlive@0f86f95f5bb92f437832f79548f92c2968f65962 # v2.0.0
#        with:
#          iamlive-version: v1.1.24
#          auto-capture: true
#          output-file: ./initial-setup-iamlive-policy-${{ env.ENVIRONMENT }}.json

      - name: Create IAM Initial Role and Policies
        working-directory: ${{ env.OPENTOFU_DIRECTORY }}/001-iam-initial-role
        id: initial-bootstrap
        env:
          TF_VAR_environment: ${{ env.ENVIRONMENT }}
        run: |
          tofu init --backend-config="bucket=${{ env.TF_VAR_bucket_name }}" --backend-config="region=${{ env.AWS_REGION }}"
          tofu fmt -check
          tofu validate
          tofu plan -var-file="../configs/opentofu-${{ env.ENVIRONMENT }}.tfvars" -out=tfplan
          tofu apply -auto-approve tfplan

#      - name: Debug - List files
#        if: always()
#        run: |
#          echo "Files in root directory:"
#          ls -la ./initial-setup-iamlive-policy*.json || echo "No iamlive policy files found in root"
#          echo "Files in working directory:"
#          ls -la ${{ env.OPENTOFU_DIRECTORY }}/001-iam-initial-role/initial-setup-iamlive-policy*.json || echo "No iamlive policy files found in working directory"
#
#      - name: Upload IAM Live Policy
#        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
#        if: always()
#        with:
#          name: initial-setup-iamlive-policy-${{ env.ENVIRONMENT }}-${{ github.run_id }}
#          path: ./initial-setup-iamlive-policy-${{ env.ENVIRONMENT }}.json
#          retention-days: 1