// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
import type { IncomingMessage, ServerResponse } from "node:http";

import {
  LOCAL_IDC_PRINCIPAL_ID,
  type LocalIsbRole,
} from "../../shared/names.js";
import type { KeyPair } from "../jwks.js";
import { mintLocalIdToken } from "../mint-token.js";
import { corsHeaders } from "./cors.js";

/**
 * The single local identity. Roles come from this server-side constant and
 * never from request input, so a developer cannot escalate by editing a claim
 * in the browser — and there is no code path where a request could influence
 * what gets signed. `satisfies` ties the role to the production enum, so a
 * rename there is a compile error here rather than a 403 that reads like an
 * RBAC bug.
 *
 * `sub` is `LOCAL_IDC_PRINCIPAL_ID` rather than a readable handle because
 * `mintLocalIdToken` copies it into `custom:idc_user_id`, which the API parses
 * as an IDC principal id; the seed keys the admin principal on the same value.
 */
const LOCAL_USER = {
  sub: LOCAL_IDC_PRINCIPAL_ID,
  email: "admin@example.local",
  roles: ["Admin"] satisfies readonly LocalIsbRole[],
};

/**
 * Mints the ID token the frontend's local Amplify providers consume.
 *
 * This route is the one the browser calls cross-origin, so the response carries
 * `corsHeaders(req)`; see `cors.ts` for why and for what it deliberately does
 * not allow. The headers go on the *success* response only, which is the only
 * one whose body is worth reading cross-origin: the 500 below is generated by
 * `server.ts` and deliberately says nothing about the identity.
 */
export async function handleSession(
  req: IncomingMessage,
  res: ServerResponse,
  keyPair: KeyPair,
): Promise<void> {
  const token = await mintLocalIdToken({ keyPair, ...LOCAL_USER });
  // The provider wants the claims object alongside the signed string, so it is
  // decoded from the token that was actually produced rather than rebuilt.
  const payload = JSON.parse(
    Buffer.from(token.split(".")[1], "base64url").toString("utf-8"),
  );
  res.writeHead(200, {
    "content-type": "application/json",
    "cache-control": "no-store",
    ...corsHeaders(req),
  });
  res.end(JSON.stringify({ token, payload }));
}
